name: BTernaryTau
title: Technically Exists
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
paginate: 5
paginate_path: "/page:num/"
plugins:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-seo-tag
