name: BTernaryTau
title: Technically Exists
markdown: kramdown
excerpt_separator: "<!--break-->"
permalink: /:year/:month/:day/:title
paginate: 5
paginate_path: "/page:num/"
baseurl: ""
plugins:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-seo-tag
host: 0.0.0.0
