name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - release

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # The checkout action doesn't provide a way to get all commit history for a single branch
          # So we use the magic number 2147483647 here which means infinite depth for git fetch
          # See https://github.com/actions/checkout/issues/520, https://stackoverflow.com/a/6802238
          fetch-depth: 2147483647

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Run custom build script
      - shell: bash
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./script/build.sh
